apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-nodejs-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-nodejs
  template:
    metadata:
      labels:
        app: nginx-nodejs
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 8080
        - name: nodejs
          image: aoskrypnik/node-web-app:2023-03-28-20-57-31
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
