apiVersion: v1
kind: Service
metadata:
  name: nginx-nodejs-service
spec:
  selector:
    app: nginx-nodejs
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30030
